### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by CommandCracker8** [Sk1erLLC/UniversalCraft#12]
Could this be adapted for plugins? Just for like things like nms which aren't multiversion compatible.

**Comment by Sychic** [comment]
Replaymod's preprocessor isn't built for Spigot, it was built for interfacing directly with Minecraft classes. We're also not server developers, so there's no interest in creating a server-side project similar to this.

**Comment by CommandCracker8** [comment]
Ah okay. I wasn't asking if you were considering making a version, just asking if it's possible to adapt this. Thanks anyway!
